// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotoCalAPI;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MotoCalAPI.Migrations
{
    [DbContext(typeof(MotoCalAPIContext))]
    partial class MotoCalAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MotoCalAPI.Models.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Series");

                    b.HasData(
                        new { Id = -1, Name = "Formula 1" },
                        new { Id = -2, Name = "Formula E" },
                        new { Id = -3, Name = "World Endurance Championship" },
                        new { Id = -4, Name = "Indy Car" },
                        new { Id = -5, Name = "MotoGP" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
